# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-12 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170709_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([]),
        ),
    ]
