# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.CharField(default='', max_length=1023, verbose_name='desciption'),
            preserve_default=False,
        ),
    ]
