# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20170207_1347'),
        ('students', '0002_auto_20170103_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='team',
        ),
        migrations.AddField(
            model_name='student',
            name='teams',
            field=models.ManyToManyField(blank=True, to='common.Team', verbose_name='teams'),
        ),
    ]
