# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.CharField(max_length=1023, verbose_name='description'),
        ),
    ]
