# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 17:46
from __future__ import unicode_literals
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('lecturers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='desciption')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Course', verbose_name='course')),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lecturers.Lecturer', verbose_name='lecturer')),
            ],
            options={
                'ordering': ['lecturer', 'course', 'title'],
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Course', verbose_name='course')),
                ('project_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Project', verbose_name='project preference')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Team', verbose_name='team assigned'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('lecturer', 'title')]),
        ),
    ]
