# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20161229_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_assigned',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Team', verbose_name='team assigned'),
        ),
    ]
