# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20170205_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=6, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([]),
        ),
    ]
