# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20170709_1808'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filedata', models.BinaryField()),
                ('filename', models.CharField(max_length=255, verbose_name='filename')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Team', verbose_name='team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('team', 'project')]),
        ),
    ]
