# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180101_2252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([]),
        ),
    ]
